--- 
hosts: 
  - 
    autostart: true
    box: Makr44/ubuntu2104-desktop
    branch: ~
    gateway: "172.17.1.1"
    identifier: mongodb.prominic.work
    ip: "192.168.2.15"
    mac: 52540fc9cf12
    folders:
      -
        map: ./conf
        to: /vagrant
    name: mongodb.prominic.work
    netmask: "255.255.255.0"
    provider:
      -
        directive: memory
        value: "8096"
      -
        directive: cpus
        value: "4"
    provision: 
      - "./scripts/aliases.sh"
path: "."
