---
hosts:
  -
    autostart: true
    box: Makr44/ubuntu2104-desktop
    branch:
    gateway: "172.17.1.1"
    identifier: session-observer-01.prominic.work    
    ip: "172.17.205.35"
    mac: 52540fc9cf12
    email: support@prominic.net
    git_user: "MarkProminic"
    letsencrypt: True
    enable_jenkins_ssl: True
    letsencrypt_certbot_renewal_days: "70"
    ssl_passphrase: "PromVagrant21"
    jenkins_https_port: "443"
    folders:
      -
        map: ./conf
        to: /vagrant
    name: session-observer-01.prominic.work
    netmask: "255.255.0.0"
    provider:
      -
        directive: memory
        value: "8096"
      -
        directive: cpus
        value: "4"
    provision: 
      - "./scripts/aliases.sh"
path: "."
