--- 
hosts: 
  - 
    autostart: true
    box: Makr44/ubuntu2104-desktop
    branch: ~
    email: support@prominic.net
    enable_jenkins_ssl: true
    gateway: "172.17.1.1"
    git_user: MarkProminic
    identifier: mongodb.prominic.work
    ip: "192.168.2.15"
    letsencrypt: true
    mac: 52540fc9cf12
    letsencrypt_certbot_renewal_days: "70"
    ssl_passphrase: "SomePassword"
    jenkins_https_port: "443"
 folders:
      -
        map: ./conf
        to: /vagrant
    name: mongodb.prominic.work
    netmask: "255.255.255.0"
    provider:
      -
        directive: memory
        value: "8096"
      -
        directive: cpus
        value: "4"
    provision: 
      - "./scripts/aliases.sh"
path: "."
