--- 
- 
  apt_key: 
    state: present
    url: "https://www.mongodb.org/static/pgp/server-5.0.asc"
  name: "Adding MongoDB source Apt signing key"
- 
  lineinfile: 
    create: true
    dest: /etc/apt/sources.list.d/mongodb-org-5.0.list
    line: "deb https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse"
    state: present
  name: "Adding MongoDB repository"
- 
  apt: 
    name: "*"
    state: latest
  name: "Updating all packages to their latest version"
- 
  apt: 
    name: mongodb-org
    state: latest
    update_cache: true
  name: "Installing MongoDB Community Edition"
