--- 
- 
  become: true
  gather_facts: true
  hosts: all
  vars: 
    timezone: 'America/Chicago'
    user: prominic
    group: prominic
  pre_tasks: 
    - 
      apt: 
        force_apt_get: true
        name: aptitude
        state: present
        update_cache: yes
      name: "Ensuring Aptitude is installed."
  roles: 
    - 
      role: mongodb


