--- 
- 
  apt: 
    upgrade: dist
  name: "Ensuring all packages are updated with an apt distribution update"
- 
  become: true
  name: "Configuring xRDP Logo Image"
  template: 
    dest: "{{item.dest}}"
    mode: "0755"
    owner: prominic
    src: "{{item.src}}"
  with_items: 
    - 
      dest: "/home/{{ user }}/Downloads/griffon_logo_xrdp.bmp"
      src: ../templates/griffon_logo_xrdp.bmp
- 
  delay: 5
  get_url: 
    dest: /tmp/xrdp-installer-1.2.3.zip
    url: "{{ cnergy_download_url }}{{ xrdp_script }}"
  name: "Downloading XRDP Scripts"
  register: xrdp_scripts
  retries: 5
  until: "xrdp_scripts is success"
- 
  name: "Unpacking XRDP scripts"
  register: xrdp_unpack
  unarchive: 
    copy: false
    dest: /tmp/
    mode: a+x
    src: "{{ xrdp_scripts.dest }}"
- 
  args: 
    executable: /usr/bin/bash
  become_user: "{{ user }}"
  name: "Installing XRDP"
  register: shell_output
  shell: "/tmp/xrdp-installer-1.2.3.sh -l"
- 
  debug: 
    msg: shell_output
    verbosity: 4
- 
  lineinfile: 
    line: FuseMountName=/tmp/thinclient_drives
    path: /etc/xrdp/sesman.ini
    regexp: ^FuseMountName=
  name: "Setting Thinclient to Tmp directory"
  notify: 
    - "Restart xRDP"
- 
  lineinfile: 
    line: "unset DBUS_SESSION_BUS_ADDRESS && unset XDG_RUNTIME_DIR  && . $HOME/.profile test -x /etc/X11/Xsession"
    path: /etc/xrdp/startwm.sh
    regexp: "^test -x /etc/X11/Xsession"
  name: "Allowing Multiple Session for a user"
  notify: 
    - "Restart xRDP"
- 
  become: true
  lineinfile: 
    line: "{{item.To}}"
    path: /etc/xrdp/xrdp.ini
    regexp: "{{item.From}}"
    state: present
  name: "Updating xRDP with Custom Login"
  notify: 
    - "Restart xRDP"
    - "Restart xRDP-Sesman"
  with_items: 
    - 
      From: ls_top_window_bg_color=
      To: ls_top_window_bg_color=990539
    - 
      From: ls_width=
      To: ls_width=350
    - 
      From: ls_height=
      To: ls_height=330
    - 
      From: ls_bg_color=
      To: ls_bg_color=737373
    - 
      From: ls_title=
      To: ls_title=Prominic.NET
    - 
      From: ls_logo_x_pos=
      To: ls_logo_x_pos=130
    - 
      From: ls_logo_y_pos=
      To: ls_logo_y_pos=25
    - 
      From: ls_label_x_pos=
      To: ls_label_x_pos=30
    - 
      From: ls_label_width=
      To: ls_label_width=65
    - 
      From: ls_input_x_pos=
      To: ls_input_x_pos=110
    - 
      From: ls_input_width=
      To: ls_input_width=210
    - 
      From: ls_input_y_pos=
      To: ls_input_y_pos=150
    - 
      From: ls_btn_ok_x_pos=
      To: ls_btn_ok_x_pos=142
    - 
      From: ls_btn_ok_y_pos=
      To: ls_btn_ok_y_pos=270
    - 
      From: ls_btn_ok_width=
      To: ls_btn_ok_width=85
    - 
      From: ls_btn_ok_height=
      To: ls_btn_ok_height=30
    - 
      From: ls_btn_cancel_x_pos=
      To: ls_btn_cancel_x_pos=237
    - 
      From: ls_btn_cancel_y_pos=
      To: ls_btn_cancel_y_pos=270
    - 
      From: ls_btn_cancel_width=
      To: ls_btn_cancel_width=85
    - 
      From: ls_btn_cancel_height=
      To: ls_btn_cancel_height=30
    - 
      From: rdpdr=true
      To: rdpdr=false
    - 
      From: rdpdr=true
      To: rdpdr=false
    - 
      From: cliprdr=true
      To: cliprdr=false
- 
  name: "Restarting xRDP"
  register: shell_output
  shell: "sudo service xrdp restart && sudo service xrdp-sesman restart"
- 
  name: "Setting console to Text mode"
  register: shell_output
  shell: "systemctl set-default multi-user.target && sudo apt-get purge gnome-initial-setup -y"
- 
  cron: 
    job: "sleep 30 && sudo service xrdp restart"
    name: "Restart xRDP on reboot"
    special_time: reboot
  name: "Restarting xRDP on reboot"
