--- 
- 
  name: "Setting timezone to America/Chicago"
  timezone: 
    name: "{{ timezone }}"
- 
  apt: 
    update_cache: true
  name: "Updating System and Apps"
- 
  apt: 
    name: "{{ packages }}"
  name: "Installing Desktop Extras"
  vars: 
    packages: 
      - dbus-x11
      - gdebi
      - python3-pip
      - psutils
      - preload
- 
  apt: 
    pkg: 
      - gnome-initial-setup
    state: absent
  name: "Removing Gnome Intial Setup"
- 
  name: "Installing psutils via pip"
  pip: 
    name: psutil
- 
  become_user: "{{ user }}"
  dconf: 
    key: /org/gnome/desktop/session/idle-delay
    value: "uint32 0"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: "{{ user }}"
  dconf: 
    key: /org/gnome/desktop/screensaver/lock-enabled
    value: "false"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: "{{ user }}"
  dconf: 
    key: /org/gnome/desktop/screensaver/idle-activation-enabled
    value: "false"
  name: "Disabling Power savings and Lock Screen"
- 
  become_user: "{{ user }}"
  dconf: 
    key: /org/gnome/desktop/screensaver/ubuntu-lock-on-suspend
    value: "false"
  name: "Disabling Lock on suspend"
- 
  become: true
  name: "Disabling Power savings and Lock Screen"
  shell: "gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-timeout 0 && gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 0  && gsettings set org.gnome.desktop.screensaver idle-activation-enabled false && gsettings set org.gnome.settings-daemon.plugins.power idle-dim false && gsettings set org.gnome.desktop.session idle-delay 0 && gsettings set org.gnome.desktop.screensaver lock-enabled false"
- 
  become: true
  name: "Stopping GDM3 to allow XRDP to later start"
  shell: "systemctl disable gdm3 && service gdm3 stop && systemctl set-default multi-user && gnome-session-quit"
- 
  become: true
  copy: 
    dest: "{{item.dest}}"
    mode: "0755"
    src: "{{item.src}}"
  name: "Setting Background Image"
  with_items: 
    - 
      dest: /usr/share/backgrounds/ProminicBackground.png
      src: ../templates/ProminicBackground.png
- 
  file: 
    path: /etc/dconf/db/local.d/
    state: directory
  name: "Creating userconf local.d DB Directory"
- 
  file: 
    path: /etc/dconf/db/profile/
    state: directory
  name: "Creating userconf profile DB Directory"
- 
  become: true
  name: "Setting User Dconf settings"
  template: 
    dest: "{{item.dest}}"
    mode: "0755"
    src: "{{item.src}}"
  with_items: 
    - 
      dest: /etc/dconf/profile/user
      src: user
    - 
      dest: /etc/dconf/db/local.d/userconf
      src: userconf
- 
  command: "dconf update"
  name: "Updating dconf Configuration for all users"
- 
  lineinfile: 
    line: Prompt=never
    path: /etc/update-manager/release-upgrades
    regexp: ^Prompt=
  name: "Disabling Upgrade Prompts"
- 
  become: true
  file: 
    group: "{{ user }}"
    owner: "{{ user }}"
    path: "/home/{{ user }}/"
    recurse: true
  name: "Ensuring Home Directory is owned by {{ user }}"
